modLoader="javafml"
loaderVersion="[39,)"
license="LGPLv3"
issueTrackerURL="https://github.com/slymask3/instant-blocks/issues"

[[mods]]
modId="instantblocks"
version="1.6.5"
displayName="Instant Blocks"
updateJSONURL="https://raw.githubusercontent.com/slymask3/instant-blocks/1.19.x/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/instant-blocks"
logoFile="logo.png"
credits="Slymask3"
authors="Slymask3"
description="Generate structures or perform actions instantaneously."

[[dependencies.instantblocks]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.instantblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"