modLoader="javafml"
loaderVersion="[39,)"
license="GPLv3"
issueTrackerURL="https://github.com/ksatchkov/instant-blocks/issues"

[[mods]]
modId="instantblocks"
version="1.6.0"
displayName="Instant Blocks"
updateJSONURL="https://raw.githubusercontent.com/ksatchkov/instant-blocks/1.18.2/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/instant-blocks"
logoFile="logo.png"
credits="Slymask3"
authors="Slymask3"
description='''
This mod adds 'Instant Blocks' to the game. These blocks could be obtained from crafting, dungeon chests, village chests, etc. Each block generates a different structure upon right-clicking on the block with an Instant Wand.
'''

[[dependencies.instantblocks]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.instantblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"